name: Build Docker image

on:
  - push
  - pull_request

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      env:
        DOCKER_REPO: docker.pkg.github.com/${{ github.repository }}/fm-http-server
      run: |
        docker login docker.pkg.github.com --username jonohill --password ${{ secrets.GITHUB_TOKEN }}
        docker pull $DOCKER_REPO:latest || true
        short_sha=$(printf ${{ github.sha }} | cut -c 1-7)
        docker build . --tag ci --cache-from $DOCKER_REPO:latest
        docker tag ci $DOCKER_REPO:$short_sha
        docker push $DOCKER_REPO
    - name: release
      if: github.ref == 'master'
      run: | # TODO version tag
        docker tag ci $DOCKER_REPO:latest
        docker push $DOCKER_REPO
